name: atdc
type: drupal
language: php

flake:
  devshell:
    packages:
      - php82
      - php82Packages.composer

git:
  ignore:
    - '!/_lessons/**'

experimental:
  createTmuxStartupFile: true
  createInclusiveGitIgnoreFile: true
